In [1]:
import numpy as np

general methods for ndarray creation

In [2]:
# from Python lists
a1D = np.array([1, 2, 3, 4])

a2D = np.array([[1, 2], [3, 4]])

a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # layers of 2D arrays

In [3]:
# from Python tuples
a1D = np.array((1, 2, 3, 4))

a2D = np.array(((1, 2), (3, 4)))

a3D = np.array((((1, 2), (3, 4)), ((5, 6), (7, 8)))) # layers of 2D arrays

1 dimensional creation functions

In [4]:
# .arange ( start, stop <excluding> , step size )
a1D_one = np.arange(0, 10, 1)
print (a1D_one)

a1D_two = np.arange(0, 10, 2)
print (a1D_two)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [5]:
# .linspace ( start, stop <including> , number of elements)

a1D_one = np.linspace(0, 9, 5)
print (a1D_one) # 5 elements from 0 to 9 with equal space, 2.25

a1D_two = np.linspace(0, 10, 6)
print (a1D_two) # 6 elements from 0 to 10 with equal space, 2

a1D_three = np.linspace(0, 9, 10)
print (a1D_three) # 10 elements from 0 to 10 with equal space, 1

[0.   2.25 4.5  6.75 9.  ]
[ 0.  2.  4.  6.  8. 10.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


2 dimensional creation functions

In [6]:
# .eye ( n, m ) --> 2D identify matrix, where the elements i=j are 1 and the rest are 0

a2D_identify = np.eye(3, 5)
print (a2D_identify) # [0, 0] = 1, [1, 1] = 1, [2, 2] = 1

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [10]:
# .diag ( [list] or (tuple), starting vertical index ) --> square 2D array, n x n

# using a list

a2D_diagonal_one = np.diag([1, 2, 3])
print (a2D_diagonal_one)

a2D_diagonal_two = np.diag([1, 2, 3], 2)
print (a2D_diagonal_two)

# using a tuple

a2D_diagonal_one = np.diag((1, 2, 3))
print (a2D_diagonal_one)

a2D_diagonal_two = np.diag((5, 6, 7), 2)
print (a2D_diagonal_two)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 0 1 0 0]
 [0 0 0 2 0]
 [0 0 0 0 3]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 0 5 0 0]
 [0 0 0 6 0]
 [0 0 0 0 7]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [11]:
# .vander ( [list] or (tuple), n ) --> Vandermode matrix, where the highest polynomial order is n-1

a2D_vander_one = np.vander([1, 2, 3, 4], 5)
print (a2D_vander_one)
                           
a2D_vander_two = np.vander([1, 2, 3, 4], 3)
print (a2D_vander_two)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]]
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]


general ndarray creation functions

In [14]:
# .zeros ( x, y, z ... ) or .ones ( x, y, z ... )

print (np.zeros((2, 3)))

print (np.zeros((2, 3, 2)))

print (np.ones((2, 3)))

print (np.ones((2, 3, 2)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [20]:
# .random.random( (x, y, z, ...) ) 

a1D_random = np.random.random((5))
print (a1D_random)

a2D_random = np.random.random((5, 5))
print (a2D_random)

[0.25443203 0.3494983  0.20407296 0.4988618  0.36557464]
[[0.33151354 0.22260476 0.29138664 0.53634277 0.87876966]
 [0.58883443 0.39350681 0.80960977 0.33039882 0.37493105]
 [0.8314491  0.83415966 0.09439742 0.37817378 0.31110487]
 [0.55161377 0.40309299 0.24296118 0.1713995  0.7040352 ]
 [0.66799187 0.12832423 0.25893745 0.99107946 0.11362335]]


In [25]:
# .indices () --> returns an array representing the indices of a grid

print (np.indices((2, 3)))

print (np.indices((4, 8)))

[[[0 0 0]
  [1 1 1]]

 [[0 1 2]
  [0 1 2]]]
[[[0 0 0 0 0 0 0 0]
  [1 1 1 1 1 1 1 1]
  [2 2 2 2 2 2 2 2]
  [3 3 3 3 3 3 3 3]]

 [[0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]]]
