In [15]:
import numpy as np
from pprint import pprint
from tabulate import tabulate

# Dimensional Indexing Tools
### - Ellipsis
### - newaxis

In [2]:
# Ellipsis

a1D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

a1D_ellipsis_all = a1D[...]
print (a1D_ellipsis_all)

a1D_ellipsis_step_size_two = a1D[..., 1]
print (a1D_ellipsis_step_size_two)
a1D_ellipsis_step_size_two = a1D[..., 5]
print (a1D_ellipsis_step_size_two)

[ 1  2  3  4  5  6  7  8  9 10]
2
6


In [3]:
x = np.array( [ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12] ] )
print (x.shape)

x_ellipsis = x[..., 2]
print (x_ellipsis)

(3, 4)
[ 3  7 11]


In [8]:
x = np.array( [ [ [1, 2], [3, 4] ], [ [5, 6], [7, 8] ] ] ) # ==> 3D array
print ("shape : ", x.shape)

x_ellipsis = x[..., 1] #  ==> [2, 4] [6, 8]
print (x_ellipsis)

x_ellipsis = x[..., 1, 1] #  ==> 4, 8
print (x_ellipsis)

shape :  (2, 2, 2)
[[2 4]
 [6 8]]
[4 8]


In [4]:
# newaxis ==> to expand the dimensions

x = np.array( [ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12] ] )
print (x.shape)

x_newaxis = x[:, np.newaxis, :]
print (x_newaxis.shape)
print (x_newaxis)

(3, 4)
(3, 1, 4)
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


# Advanced Indexing

In [51]:
q = np.array( [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]) # ==> 3 by 3 array
print ("q : ")
print (tabulate(q, tablefmt="grid"), end="\n\n")

w = q[ [0, 2] ]
print ("w : ")
print (tabulate(w, tablefmt="grid"), end="\n\n")

e = q[ [0, 1], [0, 2] ]
print ("e : ")
print (e)

q : 
+---+---+---+
| 1 | 2 | 3 |
+---+---+---+
| 4 | 5 | 6 |
+---+---+---+
| 7 | 8 | 9 |
+---+---+---+

w : 
+---+---+---+
| 1 | 2 | 3 |
+---+---+---+
| 7 | 8 | 9 |
+---+---+---+

e : 
[1 6]


In [50]:
q = np.array( [ [0, 1, 2, 3], [7, 8, 9, 10], [14, 15, 16, 17], [21, 22, 23, 24] ] ) # ==> 4 by 4 array
print ("q : ")
print (tabulate(q, tablefmt="grid"), end="\n\n")

w = q[ [0, 2], 3 ] # [3, 17]
print ("w : ")
print (w)

q : 
+----+----+----+----+
|  0 |  1 |  2 |  3 |
+----+----+----+----+
|  7 |  8 |  9 | 10 |
+----+----+----+----+
| 14 | 15 | 16 | 17 |
+----+----+----+----+
| 21 | 22 | 23 | 24 |
+----+----+----+----+

w : 
[ 3 17]


# Boolean Array Indexing

In [83]:
q = np.array( [ [0, 1, 2, 3], [7, 8, 9, 10], [14, 15, 16, 17], [21, 22, 23, 24] ] ) # ==> 4 by 4 array
print ("q : ")
print (tabulate(q, tablefmt="grid"), end="\n\n")

w = q[ [True, False, True, False] ]
print ("w = q[ [True, False, True, False] ] : ")
print (tabulate(w, tablefmt="grid"), end="\n\n")

e = q >= 10
print ("e = q >= 10 : ")
print (tabulate(e, tablefmt="grid"), end="\n\n")

r = q[ e[..., 3] ]
print ("r = q[ e[..., 3] ] : ")
print (tabulate(r, tablefmt="grid"))
print ("where e[..., 3] : ", e[..., 3], end="\n\n")

q : 
+----+----+----+----+
|  0 |  1 |  2 |  3 |
+----+----+----+----+
|  7 |  8 |  9 | 10 |
+----+----+----+----+
| 14 | 15 | 16 | 17 |
+----+----+----+----+
| 21 | 22 | 23 | 24 |
+----+----+----+----+

w = q[ [True, False, True, False] ] : 
+----+----+----+----+
|  0 |  1 |  2 |  3 |
+----+----+----+----+
| 14 | 15 | 16 | 17 |
+----+----+----+----+

e = q >= 10 : 
+---+---+---+---+
| 0 | 0 | 0 | 0 |
+---+---+---+---+
| 0 | 0 | 0 | 1 |
+---+---+---+---+
| 1 | 1 | 1 | 1 |
+---+---+---+---+
| 1 | 1 | 1 | 1 |
+---+---+---+---+

r = q[ e[..., 3] ] : 
+----+----+----+----+
|  7 |  8 |  9 | 10 |
+----+----+----+----+
| 14 | 15 | 16 | 17 |
+----+----+----+----+
| 21 | 22 | 23 | 24 |
+----+----+----+----+
where e[..., 3] :  [False  True  True  True]



IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (4,) 