In [1]:
import numpy as np

general methods for ndarray creation

In [2]:
# from Python lists
a1D = np.array([1, 2, 3, 4])

a2D = np.array([[1, 2], [3, 4]])

a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # layers of 2D arrays

In [3]:
# from Python tuples
a1D = np.array((1, 2, 3, 4))

a2D = np.array(((1, 2), (3, 4)))

a3D = np.array((((1, 2), (3, 4)), ((5, 6), (7, 8)))) # layers of 2D arrays

1 dimensional creation functions

In [4]:
# .arange ( start, stop <excluding> , step size )
a1D_one = np.arange(0, 10, 1)
print (a1D_one)

a1D_two = np.arange(0, 10, 2)
print (a1D_two)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [5]:
# .linspace ( start, stop <including> , number of elements)

a1D_one = np.linspace(0, 9, 5)
print (a1D_one) # 5 elements from 0 to 9 with equal space, 2.25

a1D_two = np.linspace(0, 10, 6)
print (a1D_two) # 6 elements from 0 to 10 with equal space, 2

a1D_three = np.linspace(0, 9, 10)
print (a1D_three) # 10 elements from 0 to 10 with equal space, 1

[0.   2.25 4.5  6.75 9.  ]
[ 0.  2.  4.  6.  8. 10.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


2 dimensional creation functions

In [6]:
# .eye ( n, m ) --> 2D identify matrix, where the elements i=j are 1 and the rest are 0

a2D_identify = np.eye(3, 5)
print (a2D_identify) # [0, 0] = 1, [1, 1] = 1, [2, 2] = 1

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [7]:
# .diag ( [list] or (tuple), starting vertical index ) --> square 2D array, n x n

# using a list

a2D_diagonal_one = np.diag([1, 2, 3])
print (a2D_diagonal_one)

a2D_diagonal_two = np.diag([1, 2, 3], 2)
print (a2D_diagonal_two)

# using a tuple

a2D_diagonal_one = np.diag((1, 2, 3))
print (a2D_diagonal_one)

a2D_diagonal_two = np.diag((5, 6, 7), 2)
print (a2D_diagonal_two)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 0 1 0 0]
 [0 0 0 2 0]
 [0 0 0 0 3]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 0 5 0 0]
 [0 0 0 6 0]
 [0 0 0 0 7]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [8]:
# .vander ( [list] or (tuple), n ) --> Vandermode matrix, where the highest polynomial order is n-1

a2D_vander_one = np.vander([1, 2, 3, 4], 5)
print (a2D_vander_one)
                           
a2D_vander_two = np.vander([1, 2, 3, 4], 3)
print (a2D_vander_two)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]]
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]


general ndarray creation functions

In [9]:
# .zeros ( x, y, z ... ) or .ones ( x, y, z ... )

print (np.zeros((2, 3)))

print (np.zeros((2, 3, 2)))

print (np.ones((2, 3)))

print (np.ones((2, 3, 2)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [10]:
# .random.random( (x, y, z, ...) ) 

a1D_random = np.random.random((5))
print (a1D_random)

a2D_random = np.random.random((5, 5))
print (a2D_random)

[0.44591037 0.5761562  0.0676724  0.35138044 0.56232349]
[[8.47246844e-01 8.13922552e-01 1.34418579e-04 8.20880309e-01
  5.23639686e-01]
 [5.15969204e-01 1.75026727e-01 3.46544010e-01 7.11080903e-01
  7.44096868e-01]
 [7.07177686e-01 7.78307781e-01 1.52777557e-01 4.45733645e-02
  6.00291492e-01]
 [8.77185669e-01 8.42150793e-01 3.93094295e-01 8.76169921e-01
  9.40591353e-01]
 [6.08531191e-01 2.40311463e-01 7.09304207e-01 6.69003681e-01
  3.44113063e-01]]


In [11]:
# .indices () --> returns an array representing the indices of a grid

print (np.indices((2, 3)))

print (np.indices((4, 8)))

[[[0 0 0]
  [1 1 1]]

 [[0 1 2]
  [0 1 2]]]
[[[0 0 0 0 0 0 0 0]
  [1 1 1 1 1 1 1 1]
  [2 2 2 2 2 2 2 2]
  [3 3 3 3 3 3 3 3]]

 [[0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]
  [0 1 2 3 4 5 6 7]]]


replicating, joining, or mutating

In [12]:
a = np.array([1, 2, 3, 4, 5, 6])
print('a original =', a)

b = a[:2]
b += 1
print('a =', a, '; b =', b)

#  a new array is not created but a variable, b is created that viewed the first 2 elements of a

a original = [1 2 3 4 5 6]
a = [2 3 3 4 5 6] ; b = [2 3]


In [13]:
# to create a new copy of an array

a = np.array([1, 2, 3, 4])
print('a original =', a)

b = a[:2].copy() # <-- *** .copy()
b += 1
print('a = ', a, 'b = ', b)

a original = [1 2 3 4]
a =  [1 2 3 4] b =  [2 3]


In [14]:
# to join the existing arrays

A = np.array([[0, 0], [0, 0]])
B = np.array([[5, 5], [5, 5]])

a_vstack = np.vstack((A, B))
print (a_vstack)

a_hstack = np.hstack((A, B))
print (a_hstack)

A = np.array([[1, 1], [1, 1]])
B = np.array([[2, 2], [2, 2]])
C = np.array([[3, 3], [3, 3]])
D = np.array([[4, 4], [4, 4]])

a_block = np.block ([A, B, C, D])
print (a_block)

a_block = np.block ([[A, B], [C, D]])
print (a_block)

[[0 0]
 [0 0]
 [5 5]
 [5 5]]
[[0 0 5 5]
 [0 0 5 5]]
[[1 1 2 2 3 3 4 4]
 [1 1 2 2 3 3 4 4]]
[[1 1 2 2]
 [1 1 2 2]
 [3 3 4 4]
 [3 3 4 4]]


In [23]:
# using .loadtxt ()
a_from_csv = np.loadtxt('simple.csv', delimiter = ',', skiprows = 1)
print (a_from_csv)

# using .genfromtxt ()
from io import StringIO
s = StringIO("1, 2, 3")
a_from_csv = np.genfromtxt(s, delimiter = ',')
print (a_from_csv)

[[0. 0.]
 [1. 1.]
 [2. 4.]
 [3. 9.]]
[1. 2. 3.]
