In [1]:
import numpy as np
from pprint import pprint
from tabulate import tabulate

# Dimensional Indexing Tools
### - Ellipsis
### - newaxis

In [2]:
# Ellipsis

a1D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

a1D_ellipsis_all = a1D[...]
print (a1D_ellipsis_all)

a1D_ellipsis_step_size_two = a1D[..., 1]
print (a1D_ellipsis_step_size_two)
a1D_ellipsis_step_size_two = a1D[..., 5]
print (a1D_ellipsis_step_size_two)

[ 1  2  3  4  5  6  7  8  9 10]
2
6


In [3]:
x = np.array( [ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12] ] )
print (x.shape)

x_ellipsis = x[..., 2]
print (x_ellipsis)

(3, 4)
[ 3  7 11]


In [4]:
x = np.array( [ [ [1, 2], [3, 4] ], [ [5, 6], [7, 8] ] ] ) # ==> 3D array
print ("shape : ", x.shape)

x_ellipsis = x[..., 1] #  ==> [2, 4] [6, 8]
print (x_ellipsis)

x_ellipsis = x[..., 1, 1] #  ==> 4, 8
print (x_ellipsis)

shape :  (2, 2, 2)
[[2 4]
 [6 8]]
[4 8]


In [5]:
# newaxis ==> to expand the dimensions

x = np.array( [ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12] ] )
print (x.shape)

x_newaxis = x[:, np.newaxis, :]
print (x_newaxis.shape)
print (x_newaxis)

(3, 4)
(3, 1, 4)
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


# Advanced Indexing

In [6]:
q = np.array( [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]) # ==> 3 by 3 array
print ("q : ")
print (tabulate(q, tablefmt="grid"), end="\n\n")

w = q[ [0, 2] ]
print ("w : ")
print (tabulate(w, tablefmt="grid"), end="\n\n")

e = q[ [0, 1], [0, 2] ]
print ("e : ")
print (e)

q : 
+---+---+---+
| 1 | 2 | 3 |
+---+---+---+
| 4 | 5 | 6 |
+---+---+---+
| 7 | 8 | 9 |
+---+---+---+

w : 
+---+---+---+
| 1 | 2 | 3 |
+---+---+---+
| 7 | 8 | 9 |
+---+---+---+

e : 
[1 6]


In [7]:
q = np.array( [ [0, 1, 2, 3], [7, 8, 9, 10], [14, 15, 16, 17], [21, 22, 23, 24] ] ) # ==> 4 by 4 array
print ("q : ")
print (tabulate(q, tablefmt="grid"), end="\n\n")

w = q[ [0, 2], 3 ] # [3, 17]
print ("w : ")
print (w)

q : 
+----+----+----+----+
|  0 |  1 |  2 |  3 |
+----+----+----+----+
|  7 |  8 |  9 | 10 |
+----+----+----+----+
| 14 | 15 | 16 | 17 |
+----+----+----+----+
| 21 | 22 | 23 | 24 |
+----+----+----+----+

w : 
[ 3 17]


# Boolean Array Indexing

In [8]:
q = np.array( [ [0, 1, 2, 3], [7, 8, 9, 10], [14, 15, 16, 17], [21, 22, 23, 24] ] ) # ==> 4 by 4 array
print ("q : ")
print (tabulate(q, tablefmt="grid"), end="\n\n")

w = q[ [True, False, True, False] ]
print ("w = q[ [True, False, True, False] ] : ")
print (tabulate(w, tablefmt="grid"), end="\n\n")

e = q >= 10
print ("e = q >= 10 : ")
print (tabulate(e, tablefmt="grid"), end="\n\n")

r = q[ e[..., 3] ]
print ("r = q[ e[..., 3] ] : ")
print (tabulate(r, tablefmt="grid"))
print ("where e[..., 3] : ", e[..., 3], end="\n\n")

q : 
+----+----+----+----+
|  0 |  1 |  2 |  3 |
+----+----+----+----+
|  7 |  8 |  9 | 10 |
+----+----+----+----+
| 14 | 15 | 16 | 17 |
+----+----+----+----+
| 21 | 22 | 23 | 24 |
+----+----+----+----+

w = q[ [True, False, True, False] ] : 
+----+----+----+----+
|  0 |  1 |  2 |  3 |
+----+----+----+----+
| 14 | 15 | 16 | 17 |
+----+----+----+----+

e = q >= 10 : 
+---+---+---+---+
| 0 | 0 | 0 | 0 |
+---+---+---+---+
| 0 | 0 | 0 | 1 |
+---+---+---+---+
| 1 | 1 | 1 | 1 |
+---+---+---+---+
| 1 | 1 | 1 | 1 |
+---+---+---+---+

r = q[ e[..., 3] ] : 
+----+----+----+----+
|  7 |  8 |  9 | 10 |
+----+----+----+----+
| 14 | 15 | 16 | 17 |
+----+----+----+----+
| 21 | 22 | 23 | 24 |
+----+----+----+----+
where e[..., 3] :  [False  True  True  True]



# ?? Field Access
- Dictionary like ndarray

In [9]:
x = np.zeros( (2, 2), dtype=[ ('a', np.int32), ('b', np.float64, (3, 3)) ] )
print (x)
print (tabulate(x['a'], tablefmt="grid"))
print (tabulate(x['b'], tablefmt="grid"))

q = np.array( [ [0, 1, 2, 3], [7, 8, 9, 10], [14, 15, 16, 17] ], dtype= [ ('w', np.int32), ('e', np.int32), ('r', np.int32) ] )

w = q['w']
print (w, end="\n\n")

e = q['e']
print (e, end="\n\n")

r = q['r']
print (r, end="\n\n")

[[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
 [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]]
+---+---+
| 0 | 0 |
+---+---+
| 0 | 0 |
+---+---+
+--------------+--------------+
| [[0. 0. 0.]  | [[0. 0. 0.]  |
|  [0. 0. 0.]  |  [0. 0. 0.]  |
|  [0. 0. 0.]] |  [0. 0. 0.]] |
+--------------+--------------+
| [[0. 0. 0.]  | [[0. 0. 0.]  |
|  [0. 0. 0.]  |  [0. 0. 0.]  |
|  [0. 0. 0.]] |  [0. 0. 0.]] |
+--------------+--------------+
[[ 0  1  2  3]
 [ 7  8  9 10]
 [14 15 16 17]]

[[ 0  1  2  3]
 [ 7  8  9 10]
 [14 15 16 17]]

[[ 0  1  2  3]
 [ 7  8  9 10]
 [14 15 16 17]]



# Assigning Values to Indexed Arrays

In [10]:
q = np.arange(10)
print (q, end="\n\n")

q[2:7] = 1
print (q, end="\n\n")

q[2:7] = np.zeros(len(q[2:7]))
print (q, end="\n\n")

[0 1 2 3 4 5 6 7 8 9]

[0 1 1 1 1 1 1 7 8 9]

[0 1 0 0 0 0 0 7 8 9]



In [11]:
w = np.arange(0, 50, 10)
print (w, end="\n\n")

w[np.array([1, 1, 3, 1])] += 1
print (w, end="\n\n")

# The 1st location only incremented by 1 because a new array is extracted from the original (as a temporary) containing the values at 1, 1, 3, 1, then the value 1 is added to the temporary, and then the temporary is assigned back to the original array.
# Thus the value of the array at x[1] + 1 is assigned to x[1] three times, rather than being incremented 3 times.

[ 0 10 20 30 40]

[ 0 11 20 31 40]

