In [1]:
import numpy as np
from io import StringIO
from pprint import pprint
from tabulate import tabulate

# Broadcasting
- broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations

In [2]:
q = np.array( [ [1, 2, 3], [10, 20, 30], [100, 200, 300], [1000, 2000, 3000] ] ) # 4 by 3
print (tabulate(q, tablefmt="grid"), end="\n\n")

w = np.array( [10, 10, 10] ) # 1 by 3
print (w, end="\n\n")

e = q + w # w stretched to 4 by 3 array
print (tabulate(e, tablefmt="grid"), end="\n\n")

+------+------+------+
|    1 |    2 |    3 |
+------+------+------+
|   10 |   20 |   30 |
+------+------+------+
|  100 |  200 |  300 |
+------+------+------+
| 1000 | 2000 | 3000 |
+------+------+------+

[10 10 10]

+------+------+------+
|   11 |   12 |   13 |
+------+------+------+
|   20 |   30 |   40 |
+------+------+------+
|  110 |  210 |  310 |
+------+------+------+
| 1010 | 2010 | 3010 |
+------+------+------+



In [3]:
q = np.array( [1, 2, 3, 4] ) # 1 by 4
w = q[:, np.newaxis] # 4 by 1
print ("w = ")
print (tabulate(w, tablefmt="grid"), end="\n\n")

e = np.array( [10, 20, 30] ) # 1 by 3
print ("e = ")
print (e, end="\n\n")

r = w + e # w stretched to 4 by 3 & e stretched to 4 by 3
print (tabulate(r, tablefmt="grid"), end="\n\n")

w = 
+---+
| 1 |
+---+
| 2 |
+---+
| 3 |
+---+
| 4 |
+---+

e = 
[10 20 30]

+----+----+----+
| 11 | 21 | 31 |
+----+----+----+
| 12 | 22 | 32 |
+----+----+----+
| 13 | 23 | 33 |
+----+----+----+
| 14 | 24 | 34 |
+----+----+----+



In [4]:
q = np.array( [ [1, 2, 3], [10, 20, 30], [100, 200, 300], [1000, 2000, 3000] ] ) # 4 by 3
print (tabulate(q, tablefmt="grid"), end="\n\n")

w = np.array( [10, 10, 10] ) # 1 by 3
print (w, end="\n\n")

e = q * w # w stretched to 4 by 3 array
print (tabulate(e, tablefmt="grid"), end="\n\n")

+------+------+------+
|    1 |    2 |    3 |
+------+------+------+
|   10 |   20 |   30 |
+------+------+------+
|  100 |  200 |  300 |
+------+------+------+
| 1000 | 2000 | 3000 |
+------+------+------+

[10 10 10]

+-------+-------+-------+
|    10 |    20 |    30 |
+-------+-------+-------+
|   100 |   200 |   300 |
+-------+-------+-------+
|  1000 |  2000 |  3000 |
+-------+-------+-------+
| 10000 | 20000 | 30000 |
+-------+-------+-------+



In [5]:
q = np.array( [1, 2, 3, 4] ) # 1 by 4
w = np.array( [10, 20, 30] ) # 1 by 3
e = q * w
print (tabulate(e, tablefmt="grid"), end="\n\n")

ValueError: operands could not be broadcast together with shapes (4,) (3,) 